package com.hikalearning;

import android.app.Activity;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.ImageButton;
import android.widget.TabHost;
import android.widget.TabHost.TabSpec;
import android.widget.TextView;

public class HiralearnActivity extends Activity {
	TextView a,i,u,e,o,ka,ki,ku,ke,ko,sa,si,su,se,so,ta,chi,tsu,te,to,na,ni,nu,ne,no,ha,hi,hu,he,ho;
	TextView ma,mi,mu,me,mo,ya,yu,yo,ra,ri,ru,re,ro,wa,n,wo,ga,gi,gu,ge,go,za,ji,zu,ze,zo,da,di,du,de,ddo;
	TextView ba,bi,bu,be,bo,pa,pi,pu,pe,po,kya,kyu,kyo,sha,shu,sho,cha,chu,cho,nya,nyu,nyo,hya,hyu,hyo,mya,myu,myo;
	TextView rya,ryu,ryo,gya,gyu,gyo,ja,ju,jo,bya,byu,byo,pya,pyu,pyo,kos1,kos2,kos3,kos4;
	ImageButton hide,hide2;
	Boolean hidee=false,hidee2=false;
	MediaPlayer audioClick;
	 @Override
	    protected void onCreate(Bundle savedInstanceState) {
	        super.onCreate(savedInstanceState);
	        requestWindowFeature(Window.FEATURE_NO_TITLE);
	        setContentView(R.layout.activity_hiralearn);
	        TabHost tabhost = (TabHost)findViewById(R.id.tabHost);
	        tabhost.setup();
	        
	        TabSpec spec1=tabhost.newTabSpec("1");
	        spec1.setContent(R.id.tab1);
	        spec1.setIndicator("1");
	        TabSpec spec2=tabhost.newTabSpec("2");
	        spec2.setContent(R.id.tab2);
	        spec2.setIndicator("2");
	        
	        tabhost.addTab(spec1);
	        tabhost.addTab(spec2);
	        
	        a=(TextView)findViewById(R.id.hiraa); i=(TextView)findViewById(R.id.hirai);
	        u=(TextView)findViewById(R.id.hirau); e=(TextView)findViewById(R.id.hirae);
	        o=(TextView)findViewById(R.id.hirao); ka=(TextView)findViewById(R.id.hiraka);
	        ki=(TextView)findViewById(R.id.hiraki); ku=(TextView)findViewById(R.id.hiraku);
	        ke=(TextView)findViewById(R.id.hirake); ko=(TextView)findViewById(R.id.hirako);
	        sa=(TextView)findViewById(R.id.hirasa); si=(TextView)findViewById(R.id.hirasi);
	        su=(TextView)findViewById(R.id.hirasu); se=(TextView)findViewById(R.id.hirase);
	        so=(TextView)findViewById(R.id.hiraso); ta=(TextView)findViewById(R.id.hirata);
	        chi=(TextView)findViewById(R.id.hirachi); tsu=(TextView)findViewById(R.id.hiratsu);
	        te=(TextView)findViewById(R.id.hirate); to=(TextView)findViewById(R.id.hirato);
	        na=(TextView)findViewById(R.id.hirana); ni=(TextView)findViewById(R.id.hirani);
	        nu=(TextView)findViewById(R.id.hiranu); ne=(TextView)findViewById(R.id.hirane);
	        no=(TextView)findViewById(R.id.hirano); ha=(TextView)findViewById(R.id.hiraha);
	        hi=(TextView)findViewById(R.id.hirahi); hu=(TextView)findViewById(R.id.hirahu);
	        he=(TextView)findViewById(R.id.hirahe); ho=(TextView)findViewById(R.id.hiraho);
	        ma=(TextView)findViewById(R.id.hirama); mi=(TextView)findViewById(R.id.hirami);
	        mu=(TextView)findViewById(R.id.hiramu); me=(TextView)findViewById(R.id.hirame);
	        mo=(TextView)findViewById(R.id.hiramo); ya=(TextView)findViewById(R.id.hiraya);
	        yu=(TextView)findViewById(R.id.hirayu); yo=(TextView)findViewById(R.id.hirayo);
	        ra=(TextView)findViewById(R.id.hirara); ri=(TextView)findViewById(R.id.hirari);
	        ru=(TextView)findViewById(R.id.hiraru); re=(TextView)findViewById(R.id.hirare);
	        ro=(TextView)findViewById(R.id.hiraro); wa=(TextView)findViewById(R.id.hirawa);
	        n=(TextView)findViewById(R.id.hiran); wo=(TextView)findViewById(R.id.hirawo);
	        ga=(TextView)findViewById(R.id.hiraga); gi=(TextView)findViewById(R.id.hiragi);
	        gu=(TextView)findViewById(R.id.hiragu); ge=(TextView)findViewById(R.id.hirage);
	        go=(TextView)findViewById(R.id.hirago); za=(TextView)findViewById(R.id.hiraza);
	        ji=(TextView)findViewById(R.id.hiraji); zu=(TextView)findViewById(R.id.hirazu);
	        ze=(TextView)findViewById(R.id.hiraze); zo=(TextView)findViewById(R.id.hirazo);
	        da=(TextView)findViewById(R.id.hirada); di=(TextView)findViewById(R.id.hiradi);
	        du=(TextView)findViewById(R.id.hiradu); de=(TextView)findViewById(R.id.hirade);
	        ddo=(TextView)findViewById(R.id.hirado); ba=(TextView)findViewById(R.id.hiraba);
	        bi=(TextView)findViewById(R.id.hirabi); bu=(TextView)findViewById(R.id.hirabu);
	        be=(TextView)findViewById(R.id.hirabe); bo=(TextView)findViewById(R.id.hirabo);
	        pa=(TextView)findViewById(R.id.hirapa); pi=(TextView)findViewById(R.id.hirapi);
	        pu=(TextView)findViewById(R.id.hirapu); pe=(TextView)findViewById(R.id.hirape);
	        po=(TextView)findViewById(R.id.hirapo); kya=(TextView)findViewById(R.id.hirakya);
	        kyu=(TextView)findViewById(R.id.hirakyu); kyo=(TextView)findViewById(R.id.hirakyo);
	        sha=(TextView)findViewById(R.id.hirasha); shu=(TextView)findViewById(R.id.hirashu);
	        sho=(TextView)findViewById(R.id.hirasho); cha=(TextView)findViewById(R.id.hiracha);
	        chu=(TextView)findViewById(R.id.hirachu); cho=(TextView)findViewById(R.id.hiracho);
	        nya=(TextView)findViewById(R.id.hiranya); nyu=(TextView)findViewById(R.id.hiranyu);
	        nyo=(TextView)findViewById(R.id.hiranyo); hya=(TextView)findViewById(R.id.hirahya);
	        hyu=(TextView)findViewById(R.id.hirahyu); hyo=(TextView)findViewById(R.id.hirahyo);
	        mya=(TextView)findViewById(R.id.hiramya); myu=(TextView)findViewById(R.id.hiramyu);
	        myo=(TextView)findViewById(R.id.hiramyo); rya=(TextView)findViewById(R.id.hirarya);
	        ryu=(TextView)findViewById(R.id.hiraryu); ryo=(TextView)findViewById(R.id.hiraryo);
	        gya=(TextView)findViewById(R.id.hiragya); gyu=(TextView)findViewById(R.id.hiragyu);
	        gyo=(TextView)findViewById(R.id.hiragyo); ja=(TextView)findViewById(R.id.hiraja);
	        ju=(TextView)findViewById(R.id.hiraju); jo=(TextView)findViewById(R.id.hirajo);
	        bya=(TextView)findViewById(R.id.hirabya); byu=(TextView)findViewById(R.id.hirabyu);
	        byo=(TextView)findViewById(R.id.hirabyo); pya=(TextView)findViewById(R.id.hirapya);
	        pyu=(TextView)findViewById(R.id.hirapyu); pyo=(TextView)findViewById(R.id.hirapyo);
	        kos1=(TextView)findViewById(R.id.hirakos1); kos2=(TextView)findViewById(R.id.hirakos2);
	        kos3=(TextView)findViewById(R.id.hirakos3); kos4=(TextView)findViewById(R.id.hirakos4);
	        hide=(ImageButton)findViewById(R.id.buttonhide);
	        hide2=(ImageButton)findViewById(R.id.buttonhide2);
	        
	        a.setText("あ"); 
	        i.setText("い");
	        u.setText("う");
	        e.setText("え");
	        o.setText("お");
	        ka.setText("か");
	        ki.setText("き");
	        ku.setText("く");
	        ke.setText("け");
	        ko.setText("こ");
	        sa.setText("さ");
	        si.setText("し");
	        su.setText("す");
	        se.setText("せ");
	        so.setText("そ");
	        ta.setText("た");
	        chi.setText("ち");
	        tsu.setText("つ");
	        te.setText("て");
	        to.setText("と");
	        na.setText("な");
	        ni.setText("に");
	        nu.setText("ぬ");
	        ne.setText("ね");
	        no.setText("の");
	        ha.setText("は");
	        hi.setText("ひ");
	        hu.setText("ふ");
	        he.setText("へ");
	        ho.setText("ほ");
	        ma.setText("ま");
	        mi.setText("み");
	        mu.setText("む");
	        me.setText("め");
	        mo.setText("も");
	        ya.setText("や");
	        yu.setText("ゆ");
	        yo.setText("よ");
	        ra.setText("ら");
	        ri.setText("り");
	        ru.setText("る");
	        re.setText("れ");
	        ro.setText("ろ");
	        wa.setText("わ");
	        n.setText("ん");
	        wo.setText("を");
	        ga.setText("が");
	        gi.setText("ぎ");
	        gu.setText("ぐ");
	        ge.setText("げ");
	        go.setText("ご");
	        za.setText("ざ");
	        ji.setText("じ");
	        zu.setText("ず");
	        ze.setText("ぜ");
	        zo.setText("ぞ");
	        da.setText("だ");
	        di.setText("ぢ");
	        du.setText("づ");
	        de.setText("で");
	        ddo.setText("ど");
	        ba.setText("ば");
	        bi.setText("び");
	        bu.setText("ぶ");
	        be.setText("べ");
	        bo.setText("ぼ");
	        pa.setText("ぱ");
	        pi.setText("ぴ");
	        pu.setText("ぷ");
	        pe.setText("ぺ");
	        po.setText("ぽ");
	        kya.setText("きゃ");
	        kyu.setText("きゅ");
	        kyo.setText("きょ");
	        sha.setText("しゃ");
	        shu.setText("しゅ");
	        sho.setText("しょ");
	        cha.setText("ちゃ");
	        chu.setText("ちゅ");
	        cho.setText("ちょ");
	        nya.setText("にゃ");
	        nyu.setText("にゅ");
	        nyo.setText("にょ");
	        hya.setText("ひゃ");
	        hyu.setText("ひゅ");
	        hyo.setText("ひょ");
	        mya.setText("みゃ");
	        myu.setText("みゅ");
	        myo.setText("みょ");
	        rya.setText("りゃ");
	        ryu.setText("りゅ");
	        ryo.setText("りょ");
	        gya.setText("ぎゃ");
	        gyu.setText("ぎゅ");
	        gyo.setText("ぎょ");
	        ja.setText("じゃ");
	        ju.setText("じゅ");
	        jo.setText("じょ");
	        bya.setText("びゃ");
	        byu.setText("びゅ");
	        byo.setText("びょ");
	        pya.setText("ぴゃ");
	        pyu.setText("ぴゅ");
	        pyo.setText("ぴょ");
	        
	        hide.setOnClickListener(new OnClickListener() {
				
				@Override
				public void onClick(View arg0) {

					audioClick = MediaPlayer.create(getApplicationContext(), R.raw.hikaclicksound);
					audioClick.setLooping(false);
					audioClick.start();

					if(hidee==false){
						hidee=true;
						hide.setImageResource(R.drawable.unhide);
						a.append("\na");
						a.setTextSize(20);
						i.append("\ni");
						i.setTextSize(20);
						u.append("\nu");
						u.setTextSize(20);
						e.append("\ne");
						e.setTextSize(20);
						o.append("\no");
						o.setTextSize(20);
						ka.append("\nka");
						ka.setTextSize(20);
						ki.append("\nki");
						ki.setTextSize(20);
						ku.append("\nku");
						ku.setTextSize(20);
						ke.append("\nke");
						ke.setTextSize(20);
						ko.append("\nko");
						ko.setTextSize(20);
						sa.append("\nsa");
						sa.setTextSize(20);
						si.append("\nshi");
						si.setTextSize(20);
						su.append("\nsu");
						su.setTextSize(20);
						se.append("\nse");
						se.setTextSize(20);
						so.append("\nso");
						so.setTextSize(20);
						ta.append("\nta");
						ta.setTextSize(20);
						chi.append("\nchi");
						chi.setTextSize(20);
						tsu.append("\ntsu");
						tsu.setTextSize(20);
						te.append("\nte");
						te.setTextSize(20);
						to.append("\nto");
						to.setTextSize(20);
						na.append("\nna");
						na.setTextSize(20);
						ni.append("\nni");
						ni.setTextSize(20);
						nu.append("\nnu");
						nu.setTextSize(20);
						ne.append("\nne");
						ne.setTextSize(20);
						no.append("\nno");
						no.setTextSize(20);
						ha.append("\nha");
						ha.setTextSize(20);
						hi.append("\nhi");
						hi.setTextSize(20);
						hu.append("\nfu");
						hu.setTextSize(20);
						he.append("\nhe");
						he.setTextSize(20);
						ho.append("\nho");
						ho.setTextSize(20);
						ma.append("\nma");
						ma.setTextSize(20);
						mi.append("\nmi");
						mi.setTextSize(20);
						mu.append("\nmu");
						mu.setTextSize(20);
						me.append("\nme");
						me.setTextSize(20);
						mo.append("\nmo");
						mo.setTextSize(20);
						ya.append("\nya");
						ya.setTextSize(20);
						yu.append("\nyu");
						yu.setTextSize(20);
						yo.append("\nyo");
						yo.setTextSize(20);
						ra.append("\nra");
						ra.setTextSize(20);
						ri.append("\nri");
						ri.setTextSize(20);
						ru.append("\nru");
						ru.setTextSize(20);
						re.append("\nre");
						re.setTextSize(20);
						ro.append("\nro");
						ro.setTextSize(20);
						wa.append("\nwa");
						wa.setTextSize(20);
						n.append("\nn");
						n.setTextSize(20);
						wo.append("\nwo");
						wo.setTextSize(20);
						ga.append("\nga");
						ga.setTextSize(20);
						gi.append("\ngi");
						gi.setTextSize(20);
						gu.append("\ngu");
						gu.setTextSize(20);
						ge.append("\nge");
						ge.setTextSize(20);
						go.append("\ngo");
						go.setTextSize(20);
						za.append("\nza");
						za.setTextSize(20);
						ji.append("\nji");
						ji.setTextSize(20);
						zu.append("\nzu");
						zu.setTextSize(20);
						ze.append("\nze");
						ze.setTextSize(20);
						zo.append("\nzo");
						zo.setTextSize(20);
						da.append("\nda");
						da.setTextSize(20);
						di.append("\nji");
						di.setTextSize(20);
						du.append("\ndu");
						du.setTextSize(20);
						de.append("\nde");
						de.setTextSize(20);
						ddo.append("\ndo");
						ddo.setTextSize(20);
						ba.append("\nba");
						ba.setTextSize(20);
						bi.append("\nbi");
						bi.setTextSize(20);
						bu.append("\nbu");
						bu.setTextSize(20);
						be.append("\nbe");
						be.setTextSize(20);
						bo.append("\nbo");
						bo.setTextSize(20);
						pa.append("\npa");
						pa.setTextSize(20);
						pi.append("\npi");
						pi.setTextSize(20);
						pu.append("\npu");
						pu.setTextSize(20);
						pe.append("\npe");
						pe.setTextSize(20);
						po.append("\npo");
						po.setTextSize(20);
						kos1.append("\n");
						kos1.setTextSize(20);
						kos2.append("\n");
						kos2.setTextSize(20);
						kos3.append("\n");
						kos3.setTextSize(20);
						kos4.append("\n");
						kos4.setTextSize(20);
					}else{
						hidee=false;
						hide.setImageResource(R.drawable.hide);
						a.setText("あ"); 
				        i.setText("い");
				        u.setText("う");
				        e.setText("え");
				        o.setText("お");
				        ka.setText("か");
				        ki.setText("き");
				        ku.setText("く");
				        ke.setText("け");
				        ko.setText("こ");
				        sa.setText("さ");
				        si.setText("し");
				        su.setText("す");
				        se.setText("せ");
				        so.setText("そ");
				        ta.setText("た");
				        chi.setText("ち");
				        tsu.setText("つ");
				        te.setText("て");
				        to.setText("と");
				        na.setText("な");
				        ni.setText("に");
				        nu.setText("ぬ");
				        ne.setText("ね");
				        no.setText("の");
				        ha.setText("は");
				        hi.setText("ひ");
				        hu.setText("ふ");
				        he.setText("へ");
				        ho.setText("ほ");
				        ma.setText("ま");
				        mi.setText("み");
				        mu.setText("む");
				        me.setText("め");
				        mo.setText("も");
				        ya.setText("や");
				        yu.setText("ゆ");
				        yo.setText("よ");
				        ra.setText("ら");
				        ri.setText("り");
				        ru.setText("る");
				        re.setText("れ");
				        ro.setText("ろ");
				        wa.setText("わ");
				        n.setText("ん");
				        wo.setText("を");
				        ga.setText("が");
				        gi.setText("ぎ");
				        gu.setText("ぐ");
				        ge.setText("げ");
				        go.setText("ご");
				        za.setText("ざ");
				        ji.setText("じ");
				        zu.setText("ず");
				        ze.setText("ぜ");
				        zo.setText("ぞ");
				        da.setText("だ");
				        di.setText("ぢ");
				        du.setText("づ");
				        de.setText("で");
				        ddo.setText("ど");
				        ba.setText("ば");
				        bi.setText("び");
				        bu.setText("ぶ");
				        be.setText("べ");
				        bo.setText("ぼ");
				        pa.setText("ぱ");
				        pi.setText("ぴ");
				        pu.setText("ぷ");
				        pe.setText("ぺ");
				        po.setText("ぽ");
						a.setTextSize(24);
						i.setTextSize(24);
						u.setTextSize(24);
						e.setTextSize(24);
						o.setTextSize(24);
						ka.setTextSize(24);
						ki.setTextSize(24);
						ku.setTextSize(24);
						ke.setTextSize(24);
						ko.setTextSize(24);
						sa.setTextSize(24);
						si.setTextSize(24);
						su.setTextSize(24);
						se.setTextSize(24);
						so.setTextSize(24);
						ta.setTextSize(24);
						chi.setTextSize(24);
						tsu.setTextSize(24);
						te.setTextSize(24);
						to.setTextSize(24);
						na.setTextSize(24);
						ni.setTextSize(24);
						nu.setTextSize(24);
						ne.setTextSize(24);
						no.setTextSize(24);
						ha.setTextSize(24);
						hi.setTextSize(24);
						hu.setTextSize(24);
						he.setTextSize(24);
						ho.setTextSize(24);
						ma.setTextSize(24);
						mi.setTextSize(24);
						mu.setTextSize(24);
						me.setTextSize(24);
						mo.setTextSize(24);
						ya.setTextSize(24);
						yu.setTextSize(24);
						yo.setTextSize(24);
						ra.setTextSize(24);
						ri.setTextSize(24);
						ru.setTextSize(24);
						re.setTextSize(24);
						ro.setTextSize(24);
						wa.setTextSize(24);
						n.setTextSize(24);
						wo.setTextSize(24);
						ga.setTextSize(24);
						gi.setTextSize(24);
						gu.setTextSize(24);
						ge.setTextSize(24);
						go.setTextSize(24);
						za.setTextSize(24);
						ji.setTextSize(24);
						zu.setTextSize(24);
						ze.setTextSize(24);
						zo.setTextSize(24);
						da.setTextSize(24);
						di.setTextSize(24);
						du.setTextSize(24);
						de.setTextSize(24);
						ddo.setTextSize(24);
						ba.setTextSize(24);
						bi.setTextSize(24);
						bu.setTextSize(24);
						be.setTextSize(24);
						bo.setTextSize(24);
						pa.setTextSize(24);
						pi.setTextSize(24);
						pu.setTextSize(24);
						pe.setTextSize(24);
						po.setTextSize(24);
						kos1.setText("");
						kos2.setText("");
						kos3.setText("");
						kos4.setText("");
					}
					
					
				}
			});
	        hide2.setOnClickListener(new OnClickListener() {
				
				@Override
				public void onClick(View arg1) {
					if(hidee2==false){
						hidee2=true;
						hide2.setImageResource(R.drawable.unhide);
						kya.append("\nkya");
						kya.setTextSize(20);
						kyu.append("\nkyu");
						kyu.setTextSize(20);
						kyo.append("\nkyo");
						kyo.setTextSize(20);
						sha.append("\nsha");
						sha.setTextSize(20);
						shu.append("\nshu");
						shu.setTextSize(20);
						sho.append("\nsho");
						sho.setTextSize(20);
						cha.append("\ncha");
						cha.setTextSize(20);
						chu.append("\nchu");
						chu.setTextSize(20);
						cho.append("\ncho");
						cho.setTextSize(20);
						nya.append("\nnya");
						nya.setTextSize(20);
						nyu.append("\nnyu");
						nyu.setTextSize(20);
						nyo.append("\nnyo");
						nyo.setTextSize(20);
						hya.append("\nhya");
						hya.setTextSize(20);
						hyu.append("\nhyu");
						hyu.setTextSize(20);
						hyo.append("\nhyo");
						hyo.setTextSize(20);
						mya.append("\nmya");
						mya.setTextSize(20);
						myu.append("\nmyu");
						myu.setTextSize(20);
						myo.append("\nmyo");
						myo.setTextSize(20);
						rya.append("\nrya");
						rya.setTextSize(20);
						ryu.append("\nryu");
						ryu.setTextSize(20);
						ryo.append("\nryo");
						ryo.setTextSize(20);
						gya.append("\ngya");
						gya.setTextSize(20);
						gyu.append("\ngyu");
						gyu.setTextSize(20);
						gyo.append("\ngyo");
						gyo.setTextSize(20);
						ja.append("\nja");
						ja.setTextSize(20);
						ju.append("\nju");
						ju.setTextSize(20);
						jo.append("\njo");
						jo.setTextSize(20);
						bya.append("\nbya");
						bya.setTextSize(20);
						byu.append("\nbyu");
						byu.setTextSize(20);
						byo.append("\nbyo");
						byo.setTextSize(20);
						pya.append("\npya");
						pya.setTextSize(20);
						pyu.append("\npyu");
						pyu.setTextSize(20);
						pyo.append("\npyo");
						pyo.setTextSize(20);
					}else{
						hidee2=false;
						hide2.setImageResource(R.drawable.hide);
				        kya.setText("きゃ");
				        kyu.setText("きゅ");
				        kyo.setText("きょ");
				        sha.setText("しゃ");
				        shu.setText("しゅ");
				        sho.setText("しょ");
				        cha.setText("ちゃ");
				        chu.setText("ちゅ");
				        cho.setText("ちょ");
				        nya.setText("にゃ");
				        nyu.setText("にゅ");
				        nyo.setText("にょ");
				        hya.setText("ひゃ");
				        hyu.setText("ひゅ");
				        hyo.setText("ひょ");
				        mya.setText("みゃ");
				        myu.setText("みゅ");
				        myo.setText("みょ");
				        rya.setText("りゃ");
				        ryu.setText("りゅ");
				        ryo.setText("りょ");
				        gya.setText("ぎゃ");
				        gyu.setText("ぎゅ");
				        gyo.setText("ぎょ");
				        ja.setText("じゃ");
				        ju.setText("じゅ");
				        jo.setText("じょ");
				        bya.setText("びゃ");
				        byu.setText("びゅ");
				        byo.setText("びょ");
				        pya.setText("ぴゃ");
				        pyu.setText("ぴゅ");
				        pyo.setText("ぴょ");
				        kya.setTextSize(24);
				        kyu.setTextSize(24);
				        kyo.setTextSize(24);
				        sha.setTextSize(24);
				        shu.setTextSize(24);
				        sho.setTextSize(24);
				        cha.setTextSize(24);
				        chu.setTextSize(24);
				        cho.setTextSize(24);
				        nya.setTextSize(24);
				        nyu.setTextSize(24);
				        nyo.setTextSize(24);
				        hya.setTextSize(24);
				        hyu.setTextSize(24);
				        hyo.setTextSize(24);
				        mya.setTextSize(24);
				        myu.setTextSize(24);
				        myo.setTextSize(24);
				        rya.setTextSize(24);
				        ryu.setTextSize(24);
				        ryo.setTextSize(24);
				        gya.setTextSize(24);
				        gyu.setTextSize(24);
				        gyo.setTextSize(24);
				        ja.setTextSize(24);
				        ju.setTextSize(24);
				        jo.setTextSize(24);
				        bya.setTextSize(24);
				        byu.setTextSize(24);
				        byo.setTextSize(24);
				        pya.setTextSize(24);
				        pyu.setTextSize(24);
				        pyo.setTextSize(24);
					}
					
					
				}
			});
	    }
}






