package com.hikalearning;

import android.app.Activity;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.widget.ImageButton;
import android.widget.TabHost;
import android.widget.TabHost.TabSpec;
import android.widget.TextView;

public class KatalearnActivity extends Activity {
	TextView a,i,u,e,o,ka,ki,ku,ke,ko,sa,si,su,se,so,ta,chi,tsu,te,to,na,ni,nu,ne,no,ha,hi,hu,he,ho;
	TextView ma,mi,mu,me,mo,ya,yu,yo,ra,ri,ru,re,ro,wa,n,wo,ga,gi,gu,ge,go,za,ji,zu,ze,zo,da,dji,dzu,de,ddo;
	TextView ba,bi,bu,be,bo,pa,pi,pu,pe,po,kya,kyu,kyo,sha,shu,sho,she,che,cha,chu,cho,nya,nyu,nyo,hya,hyu,hyo,mya,myu,myo;
	TextView rya,ryu,ryo,gya,gyu,gyo,ja,ju,jo,je,bya,byu,byo,pya,pyu,pyo,kos1,kos2,kos3,kos4,we,wi,dyu,di,du,ti,tu,fi,fe,fo,fyu,kos01,kos02,kos03;
	ImageButton hide,hide2;
	Boolean hidee=false,hidee2=false;
	MediaPlayer audioClick;
	 @Override
	    protected void onCreate(Bundle savedInstanceState) {
	        super.onCreate(savedInstanceState);
	        requestWindowFeature(Window.FEATURE_NO_TITLE);
	        setContentView(R.layout.activity_katalearn);
	        TabHost tabhost = (TabHost)findViewById(R.id.tabHost);
	        tabhost.setup();
	        
	        TabSpec spec1=tabhost.newTabSpec("1");
	        spec1.setContent(R.id.tab1);
	        spec1.setIndicator("1");
	        TabSpec spec2=tabhost.newTabSpec("2");
	        spec2.setContent(R.id.tab2);
	        spec2.setIndicator("2");
	        
	        tabhost.addTab(spec1);
	        tabhost.addTab(spec2);
	        
	        a=(TextView)findViewById(R.id.kataa); i=(TextView)findViewById(R.id.katai);
	        u=(TextView)findViewById(R.id.katau); e=(TextView)findViewById(R.id.katae);
	        o=(TextView)findViewById(R.id.katao); ka=(TextView)findViewById(R.id.kataka);
	        ki=(TextView)findViewById(R.id.kataki); ku=(TextView)findViewById(R.id.kataku);
	        ke=(TextView)findViewById(R.id.katake); ko=(TextView)findViewById(R.id.katako);
	        sa=(TextView)findViewById(R.id.katasa); si=(TextView)findViewById(R.id.katasi);
	        su=(TextView)findViewById(R.id.katasu); se=(TextView)findViewById(R.id.katase);
	        so=(TextView)findViewById(R.id.kataso); ta=(TextView)findViewById(R.id.katata);
	        chi=(TextView)findViewById(R.id.katachi); tsu=(TextView)findViewById(R.id.katatsu);
	        te=(TextView)findViewById(R.id.katate); to=(TextView)findViewById(R.id.katato);
	        na=(TextView)findViewById(R.id.katana); ni=(TextView)findViewById(R.id.katani);
	        nu=(TextView)findViewById(R.id.katanu); ne=(TextView)findViewById(R.id.katane);
	        no=(TextView)findViewById(R.id.katano); ha=(TextView)findViewById(R.id.kataha);
	        hi=(TextView)findViewById(R.id.katahi); hu=(TextView)findViewById(R.id.katahu);
	        he=(TextView)findViewById(R.id.katahe); ho=(TextView)findViewById(R.id.kataho);
	        ma=(TextView)findViewById(R.id.katama); mi=(TextView)findViewById(R.id.katami);
	        mu=(TextView)findViewById(R.id.katamu); me=(TextView)findViewById(R.id.katame);
	        mo=(TextView)findViewById(R.id.katamo); ya=(TextView)findViewById(R.id.kataya);
	        yu=(TextView)findViewById(R.id.katayu); yo=(TextView)findViewById(R.id.katayo);
	        ra=(TextView)findViewById(R.id.katara); ri=(TextView)findViewById(R.id.katari);
	        ru=(TextView)findViewById(R.id.kataru); re=(TextView)findViewById(R.id.katare);
	        ro=(TextView)findViewById(R.id.kataro); wa=(TextView)findViewById(R.id.katawa);
	        n=(TextView)findViewById(R.id.katan); wo=(TextView)findViewById(R.id.katawo);
	        ga=(TextView)findViewById(R.id.kataga); gi=(TextView)findViewById(R.id.katagi);
	        gu=(TextView)findViewById(R.id.katagu); ge=(TextView)findViewById(R.id.katage);
	        go=(TextView)findViewById(R.id.katago); za=(TextView)findViewById(R.id.kataza);
	        ji=(TextView)findViewById(R.id.kataji); zu=(TextView)findViewById(R.id.katazu);
	        ze=(TextView)findViewById(R.id.kataze); zo=(TextView)findViewById(R.id.katazo);
	        da=(TextView)findViewById(R.id.katada); dji=(TextView)findViewById(R.id.katadji);
	        dzu=(TextView)findViewById(R.id.katadzu); de=(TextView)findViewById(R.id.katade);
	        ddo=(TextView)findViewById(R.id.katado); ba=(TextView)findViewById(R.id.kataba);
	        bi=(TextView)findViewById(R.id.katabi); bu=(TextView)findViewById(R.id.katabu);
	        be=(TextView)findViewById(R.id.katabe); bo=(TextView)findViewById(R.id.katabo);
	        pa=(TextView)findViewById(R.id.katapa); pi=(TextView)findViewById(R.id.katapi);
	        pu=(TextView)findViewById(R.id.katapu); pe=(TextView)findViewById(R.id.katape);
	        po=(TextView)findViewById(R.id.katapo); kya=(TextView)findViewById(R.id.katakya);
	        kyu=(TextView)findViewById(R.id.katakyu); kyo=(TextView)findViewById(R.id.katakyo);
	        sha=(TextView)findViewById(R.id.katasha); shu=(TextView)findViewById(R.id.katashu);
	        sho=(TextView)findViewById(R.id.katasho); cha=(TextView)findViewById(R.id.katacha);
	        chu=(TextView)findViewById(R.id.katachu); cho=(TextView)findViewById(R.id.katacho);
	        nya=(TextView)findViewById(R.id.katanya); nyu=(TextView)findViewById(R.id.katanyu);
	        nyo=(TextView)findViewById(R.id.katanyo); hya=(TextView)findViewById(R.id.katahya);
	        hyu=(TextView)findViewById(R.id.katahyu); hyo=(TextView)findViewById(R.id.katahyo);
	        mya=(TextView)findViewById(R.id.katamya); myu=(TextView)findViewById(R.id.katamyu);
	        myo=(TextView)findViewById(R.id.katamyo); rya=(TextView)findViewById(R.id.katarya);
	        ryu=(TextView)findViewById(R.id.kataryu); ryo=(TextView)findViewById(R.id.kataryo);
	        gya=(TextView)findViewById(R.id.katagya); gyu=(TextView)findViewById(R.id.katagyu);
	        gyo=(TextView)findViewById(R.id.katagyo); ja=(TextView)findViewById(R.id.kataja);
	        ju=(TextView)findViewById(R.id.kataju); jo=(TextView)findViewById(R.id.katajo);
	        bya=(TextView)findViewById(R.id.katabya); byu=(TextView)findViewById(R.id.katabyu);
	        byo=(TextView)findViewById(R.id.katabyo); pya=(TextView)findViewById(R.id.katapya);
	        pyu=(TextView)findViewById(R.id.katapyu); pyo=(TextView)findViewById(R.id.katapyo);
	        kos1=(TextView)findViewById(R.id.katakos1); kos2=(TextView)findViewById(R.id.katakos2);
	        wi=(TextView)findViewById(R.id.katawi); we=(TextView)findViewById(R.id.katawe);
	        je=(TextView)findViewById(R.id.kataje); she=(TextView)findViewById(R.id.katashe);
	        che=(TextView)findViewById(R.id.katache); ti=(TextView)findViewById(R.id.katati);
	        tu=(TextView)findViewById(R.id.katatu); di=(TextView)findViewById(R.id.katadi);
	        du=(TextView)findViewById(R.id.katadu); dyu=(TextView)findViewById(R.id.katadyu);
	        fyu=(TextView)findViewById(R.id.katafyu); fi=(TextView)findViewById(R.id.katafi);
	        fe=(TextView)findViewById(R.id.katafe); fo=(TextView)findViewById(R.id.katafo);
	        kos01=(TextView)findViewById(R.id.katakos01); kos02=(TextView)findViewById(R.id.katakos02);
	        kos03=(TextView)findViewById(R.id.katakos03);
	        
	        
	        hide=(ImageButton)findViewById(R.id.buttonhide);
	        hide2=(ImageButton)findViewById(R.id.buttonhide2);
	        
	        a.setText("ア"); 
	        i.setText("イ");
	        u.setText("ウ");
	        e.setText("エ");
	        o.setText("オ");
	        ka.setText("カ");
	        ki.setText("キ");
	        ku.setText("ク");
	        ke.setText("ケ");
	        ko.setText("コ");
	        sa.setText("サ");
	        si.setText("シ");
	        su.setText("ス");
	        se.setText("セ");
	        so.setText("ソ");
	        ta.setText("タ");
	        chi.setText("チ");
	        tsu.setText("ツ");
	        te.setText("テ");
	        to.setText("ト");
	        na.setText("ナ");
	        ni.setText("ニ");
	        nu.setText("ヌ");
	        ne.setText("ネ");
	        no.setText("ノ");
	        ha.setText("ハ");
	        hi.setText("ヒ");
	        hu.setText("フ");
	        he.setText("ヘ");
	        ho.setText("ホ");
	        ma.setText("マ");
	        mi.setText("ミ");
	        mu.setText("ム");
	        me.setText("メ");
	        mo.setText("モ");
	        ya.setText("ヤ");
	        yu.setText("ユ");
	        yo.setText("ヨ");
	        ra.setText("ラ");
	        ri.setText("リ");
	        ru.setText("ル");
	        re.setText("レ");
	        ro.setText("ロ");
	        wa.setText("ロ");
	        n.setText("ン");
	        wo.setText("ヲ");
	        ga.setText("ガ");
	        gi.setText("ギ");
	        gu.setText("グ");
	        ge.setText("ゲ");
	        go.setText("ゴ");
	        za.setText("ザ");
	        ji.setText("ジ");
	        zu.setText("ズ");
	        ze.setText("ゼ");
	        zo.setText("ゾ");
	        da.setText("ダ");
	        dji.setText("ヂ");
	        dzu.setText("ヅ");
	        de.setText("デ");
	        ddo.setText("ド");
	        ba.setText("バ");
	        bi.setText("ビ");
	        bu.setText("ブ");
	        be.setText("ベ");
	        bo.setText("ボ");
	        pa.setText("パ");
	        pi.setText("ピ");
	        pu.setText("プ");
	        pe.setText("ペ");
	        po.setText("ポ");
	        kya.setText("キャ");
	        kyu.setText("キュ");
	        kyo.setText("キョ");
	        sha.setText("シャ");
	        shu.setText("シュ");
	        she.setText("シェ");
	        sho.setText("ショ");
	        cha.setText("チャ");
	        chu.setText("チュ");
	        che.setText("チェ");
	        cho.setText("チョ");
	        nya.setText("ニャ");
	        nyu.setText("ニュ");
	        nyo.setText("ニョ");
	        hya.setText("ヒャ");
	        hyu.setText("ヒュ");
	        hyo.setText("ヒョ");
	        mya.setText("ミャ");
	        myu.setText("ミュ");
	        myo.setText("ミョ");
	        rya.setText("リャ");
	        ryu.setText("リュ");
	        ryo.setText("リョ");
	        gya.setText("ギャ");
	        gyu.setText("ギュ");
	        gyo.setText("ギョ");
	        ja.setText("ジャ");
	        ju.setText("ジュ");
	        jo.setText("ジョ");
	        je.setText("ジェ");
	        bya.setText("ビャ");
	        byu.setText("ビュ");
	        byo.setText("ビョ");
	        pya.setText("ピャ");
	        pyu.setText("ピュ");
	        pyo.setText("ピョ");
	        fi.setText("フィ");
	        fe.setText("フェ");
	        fo.setText("フォ");
	        fyu.setText("フュ");
	        dyu.setText("ドュ");
	        ti.setText("チィ");
	        tu.setText("トゥ");
	        di.setText("ヂィ");
	        du.setText("ドゥ");
	        wi.setText("ヰ");
	        we.setText("ヱ");
	        
	        hide.setOnClickListener(new OnClickListener() {
				
				@Override
				public void onClick(View arg0) {

					audioClick = MediaPlayer.create(getApplicationContext(), R.raw.hikaclicksound);
					audioClick.setLooping(false);
					audioClick.start();

					if(hidee==false){
						hidee=true;
						hide.setImageResource(R.drawable.unhide);
						a.append("\na");
						a.setTextSize(20);
						i.append("\ni");
						i.setTextSize(20);
						u.append("\nu");
						u.setTextSize(20);
						e.append("\ne");
						e.setTextSize(20);
						o.append("\no");
						o.setTextSize(20);
						ka.append("\nka");
						ka.setTextSize(20);
						ki.append("\nki");
						ki.setTextSize(20);
						ku.append("\nku");
						ku.setTextSize(20);
						ke.append("\nke");
						ke.setTextSize(20);
						ko.append("\nko");
						ko.setTextSize(20);
						sa.append("\nsa");
						sa.setTextSize(20);
						si.append("\nshi");
						si.setTextSize(20);
						su.append("\nsu");
						su.setTextSize(20);
						se.append("\nse");
						se.setTextSize(20);
						so.append("\nso");
						so.setTextSize(20);
						ta.append("\nta");
						ta.setTextSize(20);
						chi.append("\nchi");
						chi.setTextSize(20);
						tsu.append("\ntsu");
						tsu.setTextSize(20);
						te.append("\nte");
						te.setTextSize(20);
						to.append("\nto");
						to.setTextSize(20);
						na.append("\nna");
						na.setTextSize(20);
						ni.append("\nni");
						ni.setTextSize(20);
						nu.append("\nnu");
						nu.setTextSize(20);
						ne.append("\nne");
						ne.setTextSize(20);
						no.append("\nno");
						no.setTextSize(20);
						ha.append("\nha");
						ha.setTextSize(20);
						hi.append("\nhi");
						hi.setTextSize(20);
						hu.append("\nfu");
						hu.setTextSize(20);
						he.append("\nhe");
						he.setTextSize(20);
						ho.append("\nho");
						ho.setTextSize(20);
						ma.append("\nma");
						ma.setTextSize(20);
						mi.append("\nmi");
						mi.setTextSize(20);
						mu.append("\nmu");
						mu.setTextSize(20);
						me.append("\nme");
						me.setTextSize(20);
						mo.append("\nmo");
						mo.setTextSize(20);
						ya.append("\nya");
						ya.setTextSize(20);
						yu.append("\nyu");
						yu.setTextSize(20);
						yo.append("\nyo");
						yo.setTextSize(20);
						ra.append("\nra");
						ra.setTextSize(20);
						ri.append("\nri");
						ri.setTextSize(20);
						ru.append("\nru");
						ru.setTextSize(20);
						re.append("\nre");
						re.setTextSize(20);
						ro.append("\nro");
						ro.setTextSize(20);
						wa.append("\nwa");
						wa.setTextSize(20);
						n.append("\nn");
						n.setTextSize(20);
						wo.append("\nwo");
						wo.setTextSize(20);
						ga.append("\nga");
						ga.setTextSize(20);
						gi.append("\ngi");
						gi.setTextSize(20);
						gu.append("\ngu");
						gu.setTextSize(20);
						ge.append("\nge");
						ge.setTextSize(20);
						go.append("\ngo");
						go.setTextSize(20);
						za.append("\nza");
						za.setTextSize(20);
						ji.append("\nji");
						ji.setTextSize(20);
						zu.append("\nzu");
						zu.setTextSize(20);
						ze.append("\nze");
						ze.setTextSize(20);
						zo.append("\nzo");
						zo.setTextSize(20);
						da.append("\nda");
						da.setTextSize(20);
						dji.append("\nji");
						dji.setTextSize(20);
						dzu.append("\nzu");
						dzu.setTextSize(20);
						de.append("\nde");
						de.setTextSize(20);
						ddo.append("\ndo");
						ddo.setTextSize(20);
						ba.append("\nba");
						ba.setTextSize(20);
						bi.append("\nbi");
						bi.setTextSize(20);
						bu.append("\nbu");
						bu.setTextSize(20);
						be.append("\nbe");
						be.setTextSize(20);
						bo.append("\nbo");
						bo.setTextSize(20);
						pa.append("\npa");
						pa.setTextSize(20);
						pi.append("\npi");
						pi.setTextSize(20);
						pu.append("\npu");
						pu.setTextSize(20);
						pe.append("\npe");
						pe.setTextSize(20);
						po.append("\npo");
						po.setTextSize(20);
						wi.append("\nwi");
						wi.setTextSize(20);
						we.append("\nwe");
						we.setTextSize(20);
						kos1.append("\n");
						kos1.setTextSize(20);
						kos2.append("\n");
						kos2.setTextSize(20);
					}else{
						hidee=false;
						hide.setImageResource(R.drawable.hide);
						a.setText("ア"); 
				        i.setText("イ");
				        u.setText("ウ");
				        e.setText("エ");
				        o.setText("オ");
				        ka.setText("カ");
				        ki.setText("キ");
				        ku.setText("ク");
				        ke.setText("ケ");
				        ko.setText("コ");
				        sa.setText("サ");
				        si.setText("シ");
				        su.setText("ス");
				        se.setText("セ");
				        so.setText("ソ");
				        ta.setText("タ");
				        chi.setText("チ");
				        tsu.setText("ツ");
				        te.setText("テ");
				        to.setText("ト");
				        na.setText("ナ");
				        ni.setText("ニ");
				        nu.setText("ヌ");
				        ne.setText("ネ");
				        no.setText("ノ");
				        ha.setText("ハ");
				        hi.setText("ヒ");
				        hu.setText("フ");
				        he.setText("ヘ");
				        ho.setText("ホ");
				        ma.setText("マ");
				        mi.setText("ミ");
				        mu.setText("ム");
				        me.setText("メ");
				        mo.setText("モ");
				        ya.setText("ヤ");
				        yu.setText("ユ");
				        yo.setText("ヨ");
				        ra.setText("ラ");
				        ri.setText("リ");
				        ru.setText("ル");
				        re.setText("レ");
				        ro.setText("ロ");
				        wa.setText("ロ");
				        n.setText("ン");
				        wo.setText("ヲ");
				        ga.setText("ガ");
				        gi.setText("ギ");
				        gu.setText("グ");
				        ge.setText("ゲ");
				        go.setText("ゴ");
				        za.setText("ザ");
				        ji.setText("ジ");
				        zu.setText("ズ");
				        ze.setText("ゼ");
				        zo.setText("ゾ");
				        da.setText("ダ");
				        dji.setText("ヂ");
				        dzu.setText("ヅ");
				        de.setText("デ");
				        ddo.setText("ド");
				        ba.setText("バ");
				        bi.setText("ビ");
				        bu.setText("ブ");
				        be.setText("ベ");
				        bo.setText("ボ");
				        pa.setText("パ");
				        pi.setText("ピ");
				        pu.setText("プ");
				        pe.setText("ペ");
				        po.setText("ポ");
				        wi.setText("ヰ");
				        we.setText("ヱ");
						a.setTextSize(24);
						i.setTextSize(24);
						u.setTextSize(24);
						e.setTextSize(24);
						o.setTextSize(24);
						ka.setTextSize(24);
						ki.setTextSize(24);
						ku.setTextSize(24);
						ke.setTextSize(24);
						ko.setTextSize(24);
						sa.setTextSize(24);
						si.setTextSize(24);
						su.setTextSize(24);
						se.setTextSize(24);
						so.setTextSize(24);
						ta.setTextSize(24);
						chi.setTextSize(24);
						tsu.setTextSize(24);
						te.setTextSize(24);
						to.setTextSize(24);
						na.setTextSize(24);
						ni.setTextSize(24);
						nu.setTextSize(24);
						ne.setTextSize(24);
						no.setTextSize(24);
						ha.setTextSize(24);
						hi.setTextSize(24);
						hu.setTextSize(24);
						he.setTextSize(24);
						ho.setTextSize(24);
						ma.setTextSize(24);
						mi.setTextSize(24);
						mu.setTextSize(24);
						me.setTextSize(24);
						mo.setTextSize(24);
						ya.setTextSize(24);
						yu.setTextSize(24);
						yo.setTextSize(24);
						ra.setTextSize(24);
						ri.setTextSize(24);
						ru.setTextSize(24);
						re.setTextSize(24);
						ro.setTextSize(24);
						wa.setTextSize(24);
						n.setTextSize(24);
						wo.setTextSize(24);
						ga.setTextSize(24);
						gi.setTextSize(24);
						gu.setTextSize(24);
						ge.setTextSize(24);
						go.setTextSize(24);
						za.setTextSize(24);
						ji.setTextSize(24);
						zu.setTextSize(24);
						ze.setTextSize(24);
						zo.setTextSize(24);
						da.setTextSize(24);
						dji.setTextSize(24);
						dzu.setTextSize(24);
						de.setTextSize(24);
						ddo.setTextSize(24);
						ba.setTextSize(24);
						bi.setTextSize(24);
						bu.setTextSize(24);
						be.setTextSize(24);
						bo.setTextSize(24);
						pa.setTextSize(24);
						pi.setTextSize(24);
						pu.setTextSize(24);
						pe.setTextSize(24);
						po.setTextSize(24);
						wi.setTextSize(24);
						we.setTextSize(24);
						kos1.setText("");
						kos2.setText("");
					}
					
					
				}
			});
	        hide2.setOnClickListener(new OnClickListener() {
				
				@Override
				public void onClick(View arg1) {
					if(hidee2==false){
						hidee2=true;
						hide2.setImageResource(R.drawable.unhide);
						kya.append("\nkya");
						kya.setTextSize(20);
						kyu.append("\nkyu");
						kyu.setTextSize(20);
						kyo.append("\nkyo");
						kyo.setTextSize(20);
						sha.append("\nsha");
						sha.setTextSize(20);
						shu.append("\nshu");
						shu.setTextSize(20);
						sho.append("\nsho");
						sho.setTextSize(20);
						cha.append("\ncha");
						cha.setTextSize(20);
						chu.append("\nchu");
						chu.setTextSize(20);
						cho.append("\ncho");
						cho.setTextSize(20);
						nya.append("\nnya");
						nya.setTextSize(20);
						nyu.append("\nnyu");
						nyu.setTextSize(20);
						nyo.append("\nnyo");
						nyo.setTextSize(20);
						hya.append("\nhya");
						hya.setTextSize(20);
						hyu.append("\nhyu");
						hyu.setTextSize(20);
						hyo.append("\nhyo");
						hyo.setTextSize(20);
						mya.append("\nmya");
						mya.setTextSize(20);
						myu.append("\nmyu");
						myu.setTextSize(20);
						myo.append("\nmyo");
						myo.setTextSize(20);
						rya.append("\nrya");
						rya.setTextSize(20);
						ryu.append("\nryu");
						ryu.setTextSize(20);
						ryo.append("\nryo");
						ryo.setTextSize(20);
						gya.append("\ngya");
						gya.setTextSize(20);
						gyu.append("\ngyu");
						gyu.setTextSize(20);
						gyo.append("\ngyo");
						gyo.setTextSize(20);
						ja.append("\nja");
						ja.setTextSize(20);
						ju.append("\nju");
						ju.setTextSize(20);
						jo.append("\njo");
						jo.setTextSize(20);
						bya.append("\nbya");
						bya.setTextSize(20);
						byu.append("\nbyu");
						byu.setTextSize(20);
						byo.append("\nbyo");
						byo.setTextSize(20);
						pya.append("\npya");
						pya.setTextSize(20);
						pyu.append("\npyu");
						pyu.setTextSize(20);
						pyo.append("\npyo");
						pyo.setTextSize(20);
						kos01.append("\n");
						kos01.setTextSize(20);
						kos02.append("\n");
						kos02.setTextSize(20);
						kos03.append("\n");
						kos03.setTextSize(20);
						she.append("\nshe");
						she.setTextSize(20);
						che.append("\nche");
						che.setTextSize(20);
						ti.append("\nti");
						ti.setTextSize(20);
						tu.append("\ntu");
						tu.setTextSize(20);
						di.append("\ndi");
						di.setTextSize(20);
						du.append("\ndu");
						du.setTextSize(20);
						dyu.append("\ndyu");
						dyu.setTextSize(20);
						fyu.append("\nfyu");
						fyu.setTextSize(20);
						fi.append("\nfi");
						fi.setTextSize(20);
						fe.append("\nfe");
						fe.setTextSize(20);
						fo.append("\nfo");
						fo.setTextSize(20);
						je.append("\nje");
						je.setTextSize(20);
					}else{
						hidee2=false;
						hide2.setImageResource(R.drawable.hide);

				        kya.setText("キャ");
				        kyu.setText("キュ");
				        kyo.setText("キョ");
				        sha.setText("シャ");
				        shu.setText("シュ");
				        she.setText("シェ");
				        sho.setText("ショ");
				        cha.setText("チャ");
				        chu.setText("チュ");
				        che.setText("チェ");
				        cho.setText("チョ");
				        nya.setText("ニャ");
				        nyu.setText("ニュ");
				        nyo.setText("ニョ");
				        hya.setText("ヒャ");
				        hyu.setText("ヒュ");
				        hyo.setText("ヒョ");
				        mya.setText("ミャ");
				        myu.setText("ミュ");
				        myo.setText("ミョ");
				        rya.setText("リャ");
				        ryu.setText("リュ");
				        ryo.setText("リョ");
				        gya.setText("ギャ");
				        gyu.setText("ギュ");
				        gyo.setText("ギョ");
				        ja.setText("ジャ");
				        ju.setText("ジュ");
				        jo.setText("ジョ");
				        je.setText("ジェ");
				        bya.setText("ビャ");
				        byu.setText("ビュ");
				        byo.setText("ビョ");
				        pya.setText("ピャ");
				        pyu.setText("ピュ");
				        pyo.setText("ピョ");
				        fi.setText("フィ");
				        fe.setText("フェ");
				        fo.setText("フォ");
				        fyu.setText("フュ");
				        dyu.setText("ドュ");
				        ti.setText("チィ");
				        tu.setText("トゥ");
				        di.setText("ヂィ");
				        du.setText("ドゥ");
				        kya.setTextSize(24);
				        kyu.setTextSize(24);
				        kyo.setTextSize(24);
				        sha.setTextSize(24);
				        shu.setTextSize(24);
				        sho.setTextSize(24);
				        cha.setTextSize(24);
				        chu.setTextSize(24);
				        cho.setTextSize(24);
				        nya.setTextSize(24);
				        nyu.setTextSize(24);
				        nyo.setTextSize(24);
				        hya.setTextSize(24);
				        hyu.setTextSize(24);
				        hyo.setTextSize(24);
				        mya.setTextSize(24);
				        myu.setTextSize(24);
				        myo.setTextSize(24);
				        rya.setTextSize(24);
				        ryu.setTextSize(24);
				        ryo.setTextSize(24);
				        gya.setTextSize(24);
				        gyu.setTextSize(24);
				        gyo.setTextSize(24);
				        ja.setTextSize(24);
				        ju.setTextSize(24);
				        jo.setTextSize(24);
				        bya.setTextSize(24);
				        byu.setTextSize(24);
				        byo.setTextSize(24);
				        pya.setTextSize(24);
				        pyu.setTextSize(24);
				        pyo.setTextSize(24);
						ti.setTextSize(24);
						tu.setTextSize(24);
						di.setTextSize(24);
						du.setTextSize(24);
						dyu.setTextSize(24);
						fyu.setTextSize(24);
						fi.setTextSize(24);
						fe.setTextSize(24);
						fo.setTextSize(24);
						she.setTextSize(24);
						che.setTextSize(24);
						je.setTextSize(24);
						kos01.setText("");
						kos02.setText("");
						kos03.setText("");
					}
					
					
				}
			});
	    }
}






